# Generated by Django 5.1.2 on 2025-10-16 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0010_homologationproduit_sous_categorie_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.CharField(max_length=255)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produits.produit')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'search_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='search_even_created_49f182_idx'), models.Index(fields=['produit', 'created_at'], name='search_even_produit_5092ce_idx'), models.Index(fields=['q', 'created_at'], name='search_even_q_b25b8b_idx')],
            },
        ),
    ]
