# Generated by Django 4.2.7 on 2025-10-01 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0005_remove_homologationproduit_uq_ph_norm_dj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comparaisonprix',
            name='magasin_prix_max',
        ),
        migrations.RemoveField(
            model_name='comparaisonprix',
            name='magasin_prix_min',
        ),
        migrations.RemoveField(
            model_name='comparaisonprix',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='historiqueprix',
            name='modifie_par',
        ),
        migrations.RemoveField(
            model_name='historiqueprix',
            name='prix',
        ),
        migrations.AlterUniqueTogether(
            name='homologationproduit',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='prix',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='prix',
            name='magasin',
        ),
        migrations.RemoveField(
            model_name='prix',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='prix',
            name='verifie_par',
        ),
        migrations.AlterUniqueTogether(
            name='prixhomologue',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='prixhomologue',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='suggestionprix',
            name='magasin',
        ),
        migrations.RemoveField(
            model_name='suggestionprix',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='suggestionprix',
            name='utilisateur',
        ),
        migrations.RemoveField(
            model_name='suggestionprix',
            name='verifie_par',
        ),
        migrations.DeleteModel(
            name='AlertePrix',
        ),
        migrations.DeleteModel(
            name='ComparaisonPrix',
        ),
        migrations.DeleteModel(
            name='HistoriquePrix',
        ),
        migrations.DeleteModel(
            name='HomologationProduit',
        ),
        migrations.DeleteModel(
            name='Prix',
        ),
        migrations.DeleteModel(
            name='PrixHomologue',
        ),
        migrations.DeleteModel(
            name='SuggestionPrix',
        ),
    ]
