# Generated by Django 5.1.2 on 2025-10-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0007_alter_categorie_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prix',
            name='devise',
            field=models.CharField(default='FCFA', max_length=10, verbose_name='Devise'),
        ),
        migrations.AddField(
            model_name='prix',
            name='type_prix',
            field=models.CharField(default='detail', max_length=20, verbose_name='Type de prix'),
        ),
        migrations.AddField(
            model_name='prix',
            name='zone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Zone'),
        ),
        migrations.AddField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
