# Generated by Django 5.1.2 on 2025-10-13 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0008_prix_devise_prix_type_prix_prix_zone_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='homologationproduit',
            unique_together={('nom', 'marque', 'format')},
        ),
    ]
