# Generated by Django 5.1.2 on 2025-10-13 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0009_alter_homologationproduit_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='homologationproduit',
            name='sous_categorie_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homologations', to='produits.categorie'),
        ),
    ]
