# Generated by Django 5.2.7 on 2025-11-15 08:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0010_homologationproduit_sous_categorie_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='prix',
            name='prix_actuel',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Prix actuel'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='quantite_unite',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Quantité par unité'),
        ),
        migrations.CreateModel(
            name='ProduitLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='produits.produit', verbose_name='Produit')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits_likes', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Produit liké',
                'verbose_name_plural': 'Produits likés',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['utilisateur', 'date_creation'], name='produits_pr_utilisa_bd577f_idx'), models.Index(fields=['produit'], name='produits_pr_produit_842943_idx')],
                'unique_together': {('utilisateur', 'produit')},
            },
        ),
    ]
