# Generated by Django 5.2.7 on 2025-11-15 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0011_alter_prix_prix_actuel_alter_produit_quantite_unite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homologationproduit',
            name='produit',
            field=models.OneToOneField(blank=True, help_text='Produit unifié dans la table principale', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homologation', to='produits.produit', verbose_name='Produit associé'),
        ),
    ]
