# Generated by Django 4.2.7 on 2025-09-24 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Région',
                'verbose_name_plural': 'Régions',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='villes', to='magasins.region')),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('type', models.CharField(choices=[('supermarche', 'Supermarché'), ('marche', 'Marché'), ('boutique', 'Boutique'), ('en_ligne', 'En ligne')], max_length=20)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='magasins', to='magasins.ville')),
            ],
            options={
                'verbose_name': 'Magasin',
                'verbose_name_plural': 'Magasins',
                'ordering': ['nom'],
            },
        ),
        migrations.AddIndex(
            model_name='ville',
            index=models.Index(fields=['region', 'nom'], name='magasins_vi_region__a6cb51_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ville',
            unique_together={('nom', 'region')},
        ),
        migrations.AddIndex(
            model_name='magasin',
            index=models.Index(fields=['slug'], name='magasins_ma_slug_67bb50_idx'),
        ),
        migrations.AddIndex(
            model_name='magasin',
            index=models.Index(fields=['ville'], name='magasins_ma_ville_i_9fe191_idx'),
        ),
    ]
