# Generated by Django 5.1.12 on 2025-09-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magasin',
            name='formatted_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='magasin',
            name='geocoded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='magasin',
            name='geocoding_provider',
            field=models.CharField(default='google', max_length=50),
        ),
        migrations.AddField(
            model_name='magasin',
            name='place_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddIndex(
            model_name='magasin',
            index=models.Index(fields=['latitude', 'longitude'], name='magasins_ma_latitud_bb6a7b_idx'),
        ),
        migrations.AddConstraint(
            model_name='magasin',
            constraint=models.CheckConstraint(check=models.Q(('latitude__isnull', True), models.Q(('latitude__gte', -90), ('latitude__lte', 90)), _connector='OR'), name='magasin_latitude_range'),
        ),
        migrations.AddConstraint(
            model_name='magasin',
            constraint=models.CheckConstraint(check=models.Q(('longitude__isnull', True), models.Q(('longitude__gte', -180), ('longitude__lte', 180)), _connector='OR'), name='magasin_longitude_range'),
        ),
    ]
