# Generated by Django 5.1.2 on 2025-10-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasins', '0003_remove_magasin_magasin_latitude_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magasin',
            name='localisation',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='magasin',
            name='type_magasin',
            field=models.CharField(blank=True, choices=[('supermarche', 'Supermarché'), ('marche', 'Marché'), ('boutique', 'Boutique'), ('en_ligne', 'En ligne')], max_length=20),
        ),
        migrations.AddField(
            model_name='magasin',
            name='zone',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddIndex(
            model_name='magasin',
            index=models.Index(fields=['zone'], name='magasins_ma_zone_4bc9a5_idx'),
        ),
    ]
