# Generated by Django 5.1.2 on 2025-10-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasins', '0004_magasin_localisation_magasin_type_magasin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magasin',
            name='formatted_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='magasin',
            name='geocoded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='magasin',
            name='geocoding_provider',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='magasin',
            name='place_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
