# Generated by Django 5.1.12 on 2025-09-26 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('magasin-magasin', 'Magasin–Magasin'), ('client-client', 'Client–Client'), ('produit-produit', 'Produit–Produit')], default='magasin-magasin', max_length=32)),
                ('params_hash', models.CharField(help_text='Hash des paramètres (fenêtre, seuils)', max_length=64)),
                ('window_start', models.DateTimeField(blank=True, null=True)),
                ('window_end', models.DateTimeField(blank=True, null=True)),
                ('node_count', models.PositiveIntegerField(default=0)),
                ('edge_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Snapshot de graphe',
                'verbose_name_plural': 'Snapshots de graphe',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type', 'created_at'], name='analyses_gr_type_2b23a4_idx'), models.Index(fields=['type', 'params_hash'], name='analyses_gr_type_c5b3b4_idx')],
                'constraints': [models.UniqueConstraint(fields=('type', 'params_hash', 'window_start', 'window_end'), name='unique_graphsnapshot_key')],
            },
        ),
        migrations.CreateModel(
            name='EdgeMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=128)),
                ('target_key', models.CharField(max_length=128)),
                ('weight', models.FloatField(default=0)),
                ('similarity', models.FloatField(default=0)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='analyses.graphsnapshot')),
            ],
            options={
                'verbose_name': "Métrique d'arête",
                'verbose_name_plural': "Métriques d'arête",
                'indexes': [models.Index(fields=['snapshot', 'source_key', 'target_key'], name='analyses_ed_snapsho_09b3c2_idx'), models.Index(fields=['snapshot', 'weight'], name='analyses_ed_snapsho_1a91b3_idx')],
                'constraints': [models.CheckConstraint(check=models.Q(('source_key', models.F('target_key')), _negated=True), name='edge_no_self_loop'), models.UniqueConstraint(fields=('snapshot', 'source_key', 'target_key'), name='unique_edge_metric')],
            },
        ),
        migrations.CreateModel(
            name='NodeMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_key', models.CharField(db_index=True, max_length=128)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('degree', models.FloatField(default=0)),
                ('weightedDegree', models.FloatField(default=0)),
                ('pagerank', models.FloatField(default=0)),
                ('community', models.IntegerField(default=-1)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='analyses.graphsnapshot')),
            ],
            options={
                'verbose_name': 'Métrique de nœud',
                'verbose_name_plural': 'Métriques de nœud',
                'indexes': [models.Index(fields=['snapshot', 'node_key'], name='analyses_no_snapsho_38d555_idx'), models.Index(fields=['snapshot', 'pagerank'], name='analyses_no_snapsho_432976_idx')],
                'constraints': [models.UniqueConstraint(fields=('snapshot', 'node_key'), name='unique_node_metric')],
            },
        ),
    ]
