# Generated by Django 4.2.7 on 2025-10-01 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasins', '0002_magasin_formatted_address_magasin_geocoded_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='magasin',
            name='magasin_latitude_range',
        ),
        migrations.RemoveConstraint(
            model_name='magasin',
            name='magasin_longitude_range',
        ),
        migrations.RemoveIndex(
            model_name='magasin',
            name='magasins_ma_latitud_bb6a7b_idx',
        ),
        migrations.RemoveField(
            model_name='magasin',
            name='formatted_address',
        ),
        migrations.RemoveField(
            model_name='magasin',
            name='geocoded_at',
        ),
        migrations.RemoveField(
            model_name='magasin',
            name='geocoding_provider',
        ),
        migrations.RemoveField(
            model_name='magasin',
            name='place_id',
        ),
    ]
