# Generated by Django 5.1.12 on 2025-09-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_utilisateur_last_location_at_utilisateur_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='utilisateur',
            name='utilisateur_latitud_aace1e_idx',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='last_location_at',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='longitude',
        ),
    ]
