# Generated by Django 4.2.7 on 2025-10-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_remove_utilisateur_utilisateur_latitud_aace1e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='last_location_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['latitude', 'longitude'], name='utilisateur_latitud_aace1e_idx'),
        ),
    ]
