# Generated by Django 4.2.7 on 2025-09-24 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AddField(
            model_name='produit',
            name='marque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='produits.marque', verbose_name='Marque'),
        ),
        migrations.AddField(
            model_name='produit',
            name='unite_mesure',
            field=models.ForeignKey(help_text='Unité principale de mesure du produit', on_delete=django.db.models.deletion.PROTECT, to='produits.unitemesure', verbose_name='Unité de mesure'),
        ),
        migrations.AddIndex(
            model_name='marque',
            index=models.Index(fields=['slug'], name='produits_ma_slug_1391d5_idx'),
        ),
        migrations.AddField(
            model_name='historiqueprixproduit',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_prix', to='produits.produit', verbose_name='Produit'),
        ),
        migrations.AddField(
            model_name='categorie',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='produits.categorie', verbose_name='Catégorie parente'),
        ),
        migrations.AddField(
            model_name='caracteristiqueproduit',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristiques', to='produits.produit', verbose_name='Produit'),
        ),
        migrations.AddField(
            model_name='avisproduit',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='produits.produit', verbose_name='Produit'),
        ),
        migrations.AddField(
            model_name='avisproduit',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis_produits', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['code_barre'], name='produits_pr_code_ba_6aba8a_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['slug'], name='produits_pr_slug_e18bf1_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['categorie'], name='produits_pr_categor_b80ae3_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['marque'], name='produits_pr_marque__b7e92d_idx'),
        ),
        migrations.AddIndex(
            model_name='produit',
            index=models.Index(fields=['est_actif'], name='produits_pr_est_act_724b33_idx'),
        ),
        migrations.AddIndex(
            model_name='historiqueprixproduit',
            index=models.Index(fields=['produit', 'date'], name='produits_hi_produit_e89c92_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='historiqueprixproduit',
            unique_together={('produit', 'date')},
        ),
        migrations.AddIndex(
            model_name='categorie',
            index=models.Index(fields=['slug'], name='produits_ca_slug_2a8b97_idx'),
        ),
        migrations.AddIndex(
            model_name='categorie',
            index=models.Index(fields=['parent'], name='produits_ca_parent__e6dd69_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='caracteristiqueproduit',
            unique_together={('produit', 'nom')},
        ),
        migrations.AddIndex(
            model_name='avisproduit',
            index=models.Index(fields=['produit', 'note'], name='produits_av_produit_17907c_idx'),
        ),
        migrations.AddIndex(
            model_name='avisproduit',
            index=models.Index(fields=['utilisateur'], name='produits_av_utilisa_7dd7bd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='avisproduit',
            unique_together={('produit', 'utilisateur')},
        ),
    ]
