# Generated by Django 5.1.12 on 2025-09-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0004_homologationproduit_prix_historiqueprix_and_more'),
    ]

    # No-op: éviter le conflit de nom de contrainte déjà existante "uq_ph_norm".
    # La contrainte créée en 0004 (uq_ph_norm_dj) est conservée.
    operations = []
