"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured
from secrets import token_urlsafe

# redis est optionnel en local (ex: railway run)
try:
    import redis  # noqa: F401
    _redis_driver_available = True
except ImportError:
    redis = None  # type: ignore
    _redis_driver_available = False

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Load environment variables from a .env file if present
# Essayer plusieurs emplacements possibles pour le fichier .env
env_paths = [
    BASE_DIR / '.env',
    BASE_DIR.parent / '.env',
]
env_loaded = False
for env_path in env_paths:
    if env_path.exists():
        load_dotenv(env_path, override=True)
        env_loaded = True
        break
# Si aucun fichier .env n'a été trouvé, essayer le chargement par défaut
if not env_loaded:
    load_dotenv(BASE_DIR / '.env')
# Force client encoding for PostgreSQL at libpq level before any connection
# Allow override via env (set to 'LATIN1' if your server/cluster is Latin-1)
os.environ.setdefault('PGCLIENTENCODING', os.getenv('PGCLIENTENCODING', 'UTF8'))

# SECURITY WARNING: don't run with debug turned on in production!
_RAW_DEBUG = os.getenv('DJANGO_DEBUG', '')
# Par défaut, DEBUG=True en développement local, False en production
# En production, définir explicitement DJANGO_DEBUG=False
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes', 'y')

# Configuration de la sécurité en production
if not DEBUG:
    # En production - Configuration HTTPS et sécurité
    # Redirection HTTP vers HTTPS
    SECURE_SSL_REDIRECT = True
    # Configuration pour reverse proxy (Railway, nginx, etc.)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))  # 1 an par défaut
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Cookies sécurisés
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'None'  # Nécessaire pour les requêtes cross-origin
    CSRF_COOKIE_SAMESITE = 'None'
    # En-têtes de sécurité
    SECURE_REFERRER_POLICY = os.getenv('SECURE_REFERRER_POLICY', 'strict-origin-when-cross-origin')
    X_FRAME_OPTIONS = 'DENY'
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
else:
    # En développement
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False
    
    # Désactiver la vérification CSRF pour les tests
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost:19000',
        'http://localhost:19006',
        'http://localhost:8001',
        'http://192.168.1.67:19000',
        'http://192.168.1.67:8000',
        'http://192.168.1.67:8001',
        'http://192.168.1.65:19000',
        'http://192.168.1.65:19006',
        'http://192.168.1.65:8000',
        'http://192.168.1.65:8001',
    ]

# SECURITY WARNING: keep the secret key used in production secret!
def get_secret_key():
    """Récupère la clé secrète depuis les variables d'environnement ou génère une clé de développement."""
    # Essayer d'abord avec DJANGO_SECRET_KEY, puis avec SECRET_KEY (pour compatibilité)
    secret_key = os.getenv('DJANGO_SECRET_KEY') or os.getenv('SECRET_KEY')
    
    # Si aucune clé n'est définie, générer une clé automatiquement
    # Cela garantit que l'application démarre toujours, même si la variable d'environnement n'est pas définie
    if not secret_key:
        # Générer une clé sécurisée de 50 caractères
        secret_key = token_urlsafe(50)
        
        # Avertissement selon l'environnement
        if DEBUG:
            print('\033[93m' + 'AVERTISSEMENT: Utilisation d\'une clé secrète générée automatiquement. ' 
                  'Pour la production, définissez DJANGO_SECRET_KEY dans les variables d\'environnement.' + '\033[0m')
        else:
            # En production, avertissement plus fort mais on continue quand même
            print('\033[91m' + '⚠️  ATTENTION PRODUCTION: DJANGO_SECRET_KEY n\'est pas définie. ' 
                  'Une clé a été générée automatiquement, mais pour des raisons de sécurité, ' 
                  'définissez DJANGO_SECRET_KEY dans les variables d\'environnement. ' 
                  'Générez une clé avec: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"' + '\033[0m')
    
    # Garantir qu'une clé est toujours retournée (sécurité supplémentaire)
    if not secret_key:
        # Fallback ultime: générer une clé même si token_urlsafe a échoué (ne devrait jamais arriver)
        secret_key = token_urlsafe(50)
    
    return secret_key

# Utilisation
SECRET_KEY = get_secret_key()

# Configuration des hôtes autorisés
# Base: toujours autoriser localhost et les IPs locales pour le développement
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '192.168.1.67', '192.168.1.65']

# En production, ajouter les domaines de production
if not DEBUG:
    ALLOWED_HOSTS.extend([
        'comparo.up.railway.app',
        'comparateurdeprix.com',
        'www.comparateurdeprix.com',
        'ftp.navixtechnology.com',
        'www.ftp.navixtechnology.com',
    ])

# Si vous avez une variable d'environnement DJANGO_ALLOWED_HOSTS, elle écrasera la configuration ci-dessus
env_allowed_hosts = os.getenv('DJANGO_ALLOWED_HOSTS')
if env_allowed_hosts:
    ALLOWED_HOSTS = [h.strip() for h in env_allowed_hosts.split(',') if h.strip()]

# Garantir que les hôtes essentiels sont toujours présents (même si écrasés par env)
essential_hosts = ['localhost', '127.0.0.1', '192.168.1.67', '192.168.1.65']
for host in essential_hosts:
    if host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host)

# Autoriser automatiquement les hôtes utilisés par les clients de test Django
# (nécessaire pour les commandes comme `diagnostic_endpoints`)
test_hosts = ['testserver']
for host in test_hosts:
    if host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host)

# Garantir que les domaines de production sont toujours présents en production
if not DEBUG:
    production_hosts = [
        'comparo.up.railway.app',
        'comparateurdeprix.com',
        'www.comparateurdeprix.com',
        'ftp.navixtechnology.com',
        'www.ftp.navixtechnology.com',
    ]
    for host in production_hosts:
        if host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(host)
    
    # Ajouter automatiquement les domaines Railway si détectés
    # Railway peut utiliser différents sous-domaines, donc on vérifie aussi via variable d'env
    railway_host = os.getenv('RAILWAY_PUBLIC_DOMAIN') or os.getenv('RAILWAY_DOMAIN')
    if railway_host and railway_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(railway_host)

# Utiliser le modèle utilisateur personnalisé
AUTH_USER_MODEL = 'utilisateurs.Utilisateur'        

# Ne pas initialiser les modèles de recommandation (sklearn/xgboost) au démarrage
RECO_INIT_MODELS_ON_STARTUP = os.getenv('RECO_INIT_MODELS_ON_STARTUP', 'False').lower() in ('1', 'true', 'yes', 'y')

# Applications installées
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Applications tierces
    'rest_framework',
    'social_django',
    'django_filters',
    'corsheaders',
    'drf_spectacular',
    'rest_framework_simplejwt.token_blacklist',
    'django_otp',
    'django_otp.plugins.otp_totp',
    
    # Vos applications
    'apps.utilisateurs',
    'apps.produits',
    'apps.magasins',
    'apps.recommandations',
    'apps.analyses',
    'apps.api',
]

# Définir les origines CORS via variables d'environnement (voir plus bas). Éviter des valeurs en dur ici.

# Configuration CORS
# En développement, autoriser toutes les origines pour faciliter les tests
# En production, utiliser CORS_ALLOWED_ORIGINS avec des origines spécifiques
CORS_ALLOW_ALL_ORIGINS = DEBUG  # True seulement en développement
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    'http://localhost:19006',  # Port par défaut de l'émulateur Android
    'http://localhost:19000',  # Port par défaut de l'émulateur iOS
    'http://localhost:19001',
    'http://localhost:19002',
    'http://localhost:3000',   # Pour React en développement
    'http://192.168.1.65:19000',  # Votre adresse IP locale pour l'émulateur
    'http://192.168.1.65:19006',
    'http://192.168.1.65:8000',   # Votre serveur Django
]

# Autoriser toutes les méthodes HTTP
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Autoriser tous les en-têtes
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Configuration REST Framework (unifiée - voir plus bas pour la configuration complète)
# Cette section est commentée car la configuration complète est définie plus bas

# Configuration JWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Doit être placé avant CommonMiddleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'config.middleware.CompressionMiddleware',  # Désactivé temporairement
    # 'apps.api.compression_middleware.SmartCompressionMiddleware',  # Désactivé temporairement
    # 'apps.api.compression_middleware.JSONMinificationMiddleware',  # Désactivé temporairement
    'django.middleware.http.ConditionalGetMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
    'django_otp.middleware.OTPMiddleware',
    # 'apps.utilisateurs.middleware.AuthErrorEnhancementMiddleware',  # Désactivé temporairement
    # 'apps.api.middleware.PerformanceMonitoringMiddleware',  # Désactivé temporairement
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'config.middleware.JSONExceptionMiddleware',  # Doit être en dernier pour intercepter toutes les exceptions
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
                'config.context_processors.social_providers',
                'config.context_processors.public_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Configuration de la base de données en fonction de l'environnement
if DEBUG:
    # Configuration pour le développement local (SQLite)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # Configuration pour la production (PostgreSQL avec SSL)
    # Définir DB_ENGINE en premier pour qu'il soit disponible partout
    DB_ENGINE = os.getenv('DB_ENGINE', 'postgresql').lower()
    
    try:
        import dj_database_url  # pyright: ignore[reportMissingImports]
        
        # Utiliser DATABASE_PUBLIC_URL (Railway public) ou DATABASE_URL (Railway internal) si disponible
        # Priorité: DATABASE_PUBLIC_URL > DATABASE_URL
        database_url = os.getenv('DATABASE_PUBLIC_URL') or os.getenv('DATABASE_URL')
        
        if database_url:
            # Détecter si on est sur Railway ou en local
            # Railway utilise des domaines .railway.internal ou .railway.app
            database_url_lower = database_url.lower()
            is_railway = '.railway.internal' in database_url_lower or '.railway.app' in database_url_lower or 'railway' in database_url_lower or 'proxy.rlwy.net' in database_url_lower
            is_localhost = 'localhost' in database_url_lower or '127.0.0.1' in database_url_lower or '::1' in database_url_lower
            
            # Détecter si on exécute depuis la machine locale (pas dans Railway)
            # Si RAILWAY_ENVIRONMENT n'est pas défini, on est probablement en local
            is_running_locally = not os.getenv('RAILWAY_ENVIRONMENT') and not os.getenv('RAILWAY_PROJECT_ID')
            
            # SSL requis seulement pour Railway/Heroku distant, JAMAIS pour localhost ou exécution locale
            # Si on exécute depuis la machine locale avec railway run, désactiver SSL
            ssl_required = is_railway and not is_localhost and not is_running_locally
            
            # Forcer la désactivation SSL si c'est clairement localhost ou exécution locale
            if is_localhost or is_running_locally:
                ssl_required = False
            
            DATABASES = {
                'default': dj_database_url.config(
                    default=database_url,
                    conn_max_age=600,
                    conn_health_checks=True,
                    ssl_require=ssl_required
                )
            }
            
            # Vérifier le HOST réel après configuration pour détecter les redirections
            db_host_actual = DATABASES['default'].get('HOST', '')
            is_actually_localhost = (
                is_localhost or 
                is_running_locally or
                db_host_actual in ('localhost', '127.0.0.1', '::1') or 
                'localhost' in str(db_host_actual).lower()
            )
            
            # Si c'est localhost ou exécution locale, forcer sslmode=disable dans OPTIONS
            if is_actually_localhost:
                DATABASES['default'].setdefault('OPTIONS', {})
                DATABASES['default']['OPTIONS']['sslmode'] = 'disable'
                # Forcer aussi ssl_require à False pour dj_database_url
                ssl_required = False
            # Déterminer DB_ENGINE à partir de l'ENGINE configuré
            db_engine_name = DATABASES['default'].get('ENGINE', '')
            if 'mysql' in db_engine_name:
                DB_ENGINE = 'mysql'
            elif 'postgresql' in db_engine_name:
                DB_ENGINE = 'postgresql'
            else:
                DB_ENGINE = 'postgresql'  # Par défaut
        else:
            # Aucune URL de base de données n'est définie
            # En production Railway, DATABASE_URL ou DATABASE_PUBLIC_URL doivent être définis automatiquement
            import logging
            logger = logging.getLogger(__name__)
            
            # Vérifier si on est sur Railway
            is_railway_env = bool(os.getenv('RAILWAY_ENVIRONMENT') or os.getenv('RAILWAY_PROJECT_ID'))
            
            if is_railway_env:
                # Sur Railway, les variables DATABASE_URL doivent être définies automatiquement
                logger.error(
                    "⚠️  DATABASE_URL et DATABASE_PUBLIC_URL ne sont pas définies sur Railway.\n"
                    "Vérifiez que le service PostgreSQL est bien lié à votre service Django.\n"
                    "Dans Railway Dashboard:\n"
                    "  1. Allez dans votre service Django\n"
                    "  2. Cliquez sur 'Variables'\n"
                    "  3. Vérifiez que DATABASE_URL ou DATABASE_PUBLIC_URL est présent\n"
                    "  4. Si absent, ajoutez-le manuellement depuis le service PostgreSQL"
                )
            
            # Configuration manuelle pour la production (fallback)
            # En production Railway, NE JAMAIS utiliser localhost comme fallback
            if is_railway_env:
                # Sur Railway, si DATABASE_URL n'est pas défini, c'est une erreur de configuration
                logger.error(
                    "❌ ERREUR CRITIQUE: DATABASE_URL et DATABASE_PUBLIC_URL ne sont pas définies sur Railway.\n"
                    "L'application ne peut pas fonctionner sans connexion à la base de données.\n"
                    "Actions requises:\n"
                    "  1. Allez dans Railway Dashboard → votre service Django\n"
                    "  2. Cliquez sur 'Variables'\n"
                    "  3. Vérifiez que le service PostgreSQL est bien lié\n"
                    "  4. Si absent, ajoutez DATABASE_URL manuellement depuis le service PostgreSQL\n"
                    "  5. Redémarrez le service Django"
                )
                # Ne pas utiliser localhost en production Railway - cela causera des erreurs
                # Utiliser des valeurs vides pour forcer l'erreur explicite
                db_host = None
                db_name = None
            else:
                # En développement local uniquement, utiliser localhost comme fallback
                db_host = os.getenv('POSTGRES_HOST', 'localhost')
                db_name = os.getenv('POSTGRES_DB', 'comparateur_prix')
            
            is_local = db_host in ('localhost', '127.0.0.1', None) if db_host else True
            ssl_require_env = os.getenv('POSTGRES_SSL_REQUIRE', 'False' if is_local else 'True')
            
            if is_railway_env and (is_local or db_host is None):
                # Ne pas créer de configuration avec localhost en production Railway
                # Laisser Django échouer avec une erreur explicite
                DATABASES = {
                    'default': {
                        'ENGINE': 'django.db.backends.postgresql',
                        'NAME': '',  # Vide pour forcer l'erreur
                        'USER': '',
                        'PASSWORD': '',
                        'HOST': '',
                        'PORT': '',
                    }
                }
            else:
                DATABASES = {
                    'default': {
                        'ENGINE': 'django.db.backends.postgresql',
                        'NAME': db_name or os.getenv('POSTGRES_DB', 'comparateur_prix'),
                        'USER': os.getenv('POSTGRES_USER', 'postgres'),
                        'PASSWORD': os.getenv('POSTGRES_PASSWORD', ''),
                        'HOST': db_host or 'localhost',
                        'PORT': os.getenv('POSTGRES_PORT', '5432'),
                        'OPTIONS': {
                            'sslmode': 'require' if ssl_require_env.lower() in ('1', 'true', 'yes', 'y') else 'disable',
                            'options': '-c client_encoding=UTF8',
                        },
                    }
                }
    except ImportError:
        # Fallback: utiliser les variables d'environnement individuelles
        DB_ENGINE = os.getenv('DB_ENGINE', 'postgresql').lower()
        DB_NAME = os.getenv('DB_NAME') or os.getenv('POSTGRES_DB') or os.getenv('MYSQL_DB', 'soutenance2')
        DB_USER = os.getenv('DB_USER') or os.getenv('POSTGRES_USER') or os.getenv('MYSQL_USER', 'postgres')
        DB_PASSWORD = (
            os.getenv('DB_PASSWORD') or 
            os.getenv('POSTGRES_PASSWORD') or 
            os.getenv('MYSQL_PASSWORD') or 
            ''
        )
        DB_HOST = os.getenv('DB_HOST') or os.getenv('POSTGRES_HOST') or os.getenv('MYSQL_HOST', 'localhost')
        DB_PORT = os.getenv('DB_PORT') or os.getenv('POSTGRES_PORT') or os.getenv('MYSQL_PORT', '3306' if DB_ENGINE == 'mysql' else '5432')
        
        if DB_ENGINE == 'mysql':
            # Configuration MySQL/MariaDB
            DATABASES = {
                'default': {
                    'ENGINE': 'django.db.backends.mysql',
                    'NAME': DB_NAME,
                    'USER': DB_USER,
                    'PASSWORD': DB_PASSWORD,
                    'HOST': DB_HOST,
                    'PORT': DB_PORT,
                    'OPTIONS': {
                        'charset': 'utf8mb4',
                        'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                    },
                }
            }
        else:
            # Configuration PostgreSQL (par défaut)
            DATABASES = {
                'default': {
                    'ENGINE': 'django.db.backends.postgresql',
                    'NAME': DB_NAME,
                    'USER': DB_USER,
                    'PASSWORD': DB_PASSWORD,
                    'HOST': DB_HOST,
                    'PORT': DB_PORT,
                    'OPTIONS': {
                        # Force UTF-8 client encoding for the DB session
                        'options': '-c client_encoding=UTF8',
                    },
                },
            }

# Admin URL paramétrable (obfuscation basique en prod)
ADMIN_URL = os.getenv('DJANGO_ADMIN_URL', 'admin/')
if not ADMIN_URL.endswith('/'):
    ADMIN_URL = ADMIN_URL + '/'

# En production, exiger des identifiants sûrs et sécuriser la connexion DB
if not DEBUG:
    # Vérifier si on utilise DATABASE_PUBLIC_URL/DATABASE_URL ou des variables individuelles
    using_database_url = bool(os.getenv('DATABASE_PUBLIC_URL') or os.getenv('DATABASE_URL'))
    db_password = DATABASES['default'].get('PASSWORD', '')
    
    # Si on utilise DATABASE_URL, le mot de passe est déjà dans l'URL parsée - ne pas valider
    # Sinon, vérifier que le mot de passe est défini via les variables d'environnement
    if using_database_url:
        # DATABASE_URL est utilisé, le mot de passe est dans l'URL - pas de validation nécessaire
        pass
    elif not db_password:
        # Déterminer le nom de la variable d'environnement attendue selon le type de DB
        try:
            db_engine_var = DB_ENGINE
        except NameError:
            # Si DB_ENGINE n'existe pas, détecter depuis DATABASES
            db_engine_var = 'postgresql' if 'postgresql' in DATABASES['default']['ENGINE'] else 'mysql'
        
        if db_engine_var == 'mysql':
            expected_var = 'DB_PASSWORD ou MYSQL_PASSWORD'
        else:
            expected_var = 'DB_PASSWORD ou POSTGRES_PASSWORD'
        
        # Diagnostic: vérifier quelles variables sont présentes
        db_password_present = bool(os.getenv('DB_PASSWORD'))
        postgres_password_present = bool(os.getenv('POSTGRES_PASSWORD'))
        mysql_password_present = bool(os.getenv('MYSQL_PASSWORD'))
        
        error_msg = (
            f'Le mot de passe de la base de données doit être défini en production.\n'
            f'Type de DB détecté: {db_engine_var.upper()}\n'
            f'Variables d\'environnement vérifiées:\n'
            f'  - DB_PASSWORD: {"présente" if db_password_present else "absente"}\n'
            f'  - POSTGRES_PASSWORD: {"présente" if postgres_password_present else "absente"}\n'
            f'  - MYSQL_PASSWORD: {"présente" if mysql_password_present else "absente"}\n'
            f'Veuillez définir {expected_var} dans votre fichier .env.\n'
            f'Emplacement attendu du fichier .env: {BASE_DIR / ".env"}'
        )
        raise ImproperlyConfigured(error_msg)
    # Activer SSL vers PostgreSQL par défaut (désactivable via POSTGRES_SSL_REQUIRE=false)
    # MAIS seulement si ce n'est pas localhost
    try:
        db_engine_check = DB_ENGINE
    except NameError:
        # Si DB_ENGINE n'existe pas, détecter depuis DATABASES
        db_engine_check = 'postgresql' if 'postgresql' in DATABASES['default']['ENGINE'] else 'mysql'
    
    if db_engine_check == 'postgresql':
        db_host = DATABASES['default'].get('HOST', '')
        is_local = db_host in ('localhost', '127.0.0.1', '::1') or 'localhost' in str(db_host).lower()
        
        # Ne pas forcer SSL si c'est localhost
        if not is_local and os.getenv('POSTGRES_SSL_REQUIRE', 'True').lower() in ('1', 'true', 'yes', 'y'):
            DATABASES['default'].setdefault('OPTIONS', {})
            DATABASES['default']['OPTIONS']['sslmode'] = 'require'
        elif is_local:
            # Forcer la désactivation SSL pour localhost
            DATABASES['default'].setdefault('OPTIONS', {})
            DATABASES['default']['OPTIONS']['sslmode'] = 'disable'

# --- Social Auth (social-auth-app-django) ---
# Authentication backends: social providers + default ModelBackend
# Note: Apple is enabled only if all required keys are configured to avoid runtime errors.
# Provider credentials (configure in environment variables)
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv('GOOGLE_CLIENT_ID')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv('GOOGLE_CLIENT_SECRET')

SOCIAL_AUTH_FACEBOOK_KEY = os.getenv('FACEBOOK_APP_ID')
SOCIAL_AUTH_FACEBOOK_SECRET = os.getenv('FACEBOOK_APP_SECRET')

# Apple Sign In requires additional keys
SOCIAL_AUTH_APPLE_ID_CLIENT = os.getenv('APPLE_CLIENT_ID')
SOCIAL_AUTH_APPLE_ID_TEAM = os.getenv('APPLE_TEAM_ID')
SOCIAL_AUTH_APPLE_ID_KEY = os.getenv('APPLE_KEY_ID')
# Private key in PEM format. You can store multiline PEM as a single env var.
SOCIAL_AUTH_APPLE_ID_SECRET = os.getenv('APPLE_PRIVATE_KEY_PEM')

ENABLE_APPLE_AUTH = all([
    SOCIAL_AUTH_APPLE_ID_TEAM,
    SOCIAL_AUTH_APPLE_ID_KEY,
    SOCIAL_AUTH_APPLE_ID_SECRET,
])

AUTHENTICATION_BACKENDS = [
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',
]
if ENABLE_APPLE_AUTH:
    AUTHENTICATION_BACKENDS.insert(2, 'social_core.backends.apple.AppleIdAuth')
AUTHENTICATION_BACKENDS = tuple(AUTHENTICATION_BACKENDS)

# Login/redirect URLs
LOGIN_URL = '/connexion/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# Social Auth error handling
SOCIAL_AUTH_LOGIN_ERROR_URL = '/oauth/error/'
# In production we generally don't want to raise raw exceptions to users
SOCIAL_AUTH_RAISE_EXCEPTIONS = False

# Use JSONField if available for storing extra data
SOCIAL_AUTH_JSONFIELD_ENABLED = True
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Libreville'

USE_I18N = True

USE_TZ = True

# Celery configuration (after TIME_ZONE is defined)
# Use REDIS_URL as default broker/result backend
# Priorité: REDIS_PUBLIC_URL (Railway public) > REDIS_URL (Railway internal) > REDISCLOUD_URL
# Ne pas utiliser de fallback localhost en production (cela causerait des erreurs de connexion)
_redis_broker_url = (
    os.getenv('CELERY_BROKER_URL') or 
    os.getenv('REDIS_PUBLIC_URL') or 
    os.getenv('REDIS_URL') or 
    os.getenv('REDISCLOUD_URL')
)
# Si aucune URL Redis n'est disponible, utiliser un fallback localhost uniquement en développement local
# Ne JAMAIS utiliser localhost en production Railway
is_railway_env = bool(os.getenv('RAILWAY_ENVIRONMENT') or os.getenv('RAILWAY_PROJECT_ID'))
if not _redis_broker_url and DEBUG and not is_railway_env:
    _redis_broker_url = 'redis://localhost:6379/0'
elif not _redis_broker_url:
    # En production, ne pas définir de fallback - Celery utilisera la configuration par défaut
    # qui peut être configurée ailleurs ou désactivée
    _redis_broker_url = None
    if is_railway_env:
        logger.warning("⚠️  REDIS_URL non défini sur Railway. Celery ne fonctionnera pas correctement.")

CELERY_BROKER_URL = _redis_broker_url
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', _redis_broker_url)
CELERY_TIMEZONE = TIME_ZONE
# Retry broker connection on startup (Celery 6+ recommendation)
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = os.getenv('CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP', 'True').lower() in ('1', 'true', 'yes', 'y')

# Site URL
SITE_URL = os.getenv('SITE_URL', 'https://www.comparateurdeprix.com')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Configuration des fichiers statiques et médias
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Ajouter le répertoire static seulement s'il existe pour éviter l'avertissement
static_dir = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [static_dir] if os.path.exists(static_dir) else []

# Configuration des médias
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configuration du stockage des fichiers statiques
if not DEBUG:
    # Utilisez un stockage personnalisé pour les fichiers statiques en production
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

USE_JWT_AUTH = os.getenv('USE_JWT_AUTH', 'True' if DEBUG else 'False').lower() in ('1', 'true', 'yes', 'y')

DEFAULT_AUTH_CLASSES = []
if USE_JWT_AUTH:
    # Configuration de l'authentification JWT
    try:
        DEFAULT_AUTH_CLASSES = [
            'rest_framework_simplejwt.authentication.JWTAuthentication',
        ]
    except ImportError:
        # Si simplejwt n'est pas installé, utiliser une liste vide
        DEFAULT_AUTH_CLASSES = []

# Configuration REST Framework (unifiée)
# TEMPORAIRE: AllowAny en production pour diagnostic
_default_perms = ['rest_framework.permissions.AllowAny']  # if DEBUG else ['rest_framework.permissions.IsAuthenticatedOrReadOnly']

# Classes d'authentification par défaut
_default_auth_classes = DEFAULT_AUTH_CLASSES.copy()
if DEBUG:
    # En développement, toujours ajouter SessionAuthentication pour la browsable API
    if 'rest_framework.authentication.SessionAuthentication' not in _default_auth_classes:
        _default_auth_classes.append('rest_framework.authentication.SessionAuthentication')
    
    # En développement, si JWT n'est pas activé, l'activer automatiquement
    if not USE_JWT_AUTH and 'rest_framework_simplejwt.authentication.JWTAuthentication' not in _default_auth_classes:
        try:
            _default_auth_classes.insert(0, 'rest_framework_simplejwt.authentication.JWTAuthentication')
        except ImportError:
            pass  # Si simplejwt n'est pas installé, ignorer

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': _default_perms,
    'DEFAULT_AUTHENTICATION_CLASSES': _default_auth_classes,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    # OPTIMISÉ: Pagination intelligente
    'DEFAULT_PAGINATION_CLASS': 'apps.api.pagination.OptimizedPageNumberPagination',
    'PAGE_SIZE': 20,
    # OPTIMISÉ: Throttling intelligent
    'DEFAULT_THROTTLE_CLASSES': [
        'apps.api.throttling.SmartAnonRateThrottle',
        'apps.api.throttling.SmartUserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.getenv('DRF_THROTTLE_ANON', '100/min'),
        'user': os.getenv('DRF_THROTTLE_USER', '1000/min'),
        'burst': '10/sec',  # Pour pics de trafic
        'sustained': '1000/hour',  # Pour trafic soutenu
        'ip': '200/min',  # Par IP
        # Scopes spécifiques pour les endpoints d'auth
        'register': os.getenv('DRF_THROTTLE_REGISTER', '10/min'),
        'activate': os.getenv('DRF_THROTTLE_ACTIVATE', '30/min'),
        'login': os.getenv('DRF_THROTTLE_LOGIN', '10/min'),
    },
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Exception handler personnalisé pour améliorer les messages d'erreur 401
    'EXCEPTION_HANDLER': 'apps.utilisateurs.exceptions.custom_exception_handler',
    # Renderers
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

# En développement, ajouter la Browsable API
if DEBUG:
    REST_FRAMEWORK['DEFAULT_RENDERER_CLASSES'].append('rest_framework.renderers.BrowsableAPIRenderer')

# OpenAPI / Swagger settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Comparateur Prix API',
    'DESCRIPTION': 'Documentation API publique et interne',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# SimpleJWT configuration (si activé via USE_JWT_AUTH)
from datetime import timedelta  # noqa: E402
JWT_ALG = os.getenv('JWT_ALGORITHM', 'HS256').upper()

def _read_file_or_none(path: str):
    try:
        if not path:
            return None
        # Résoudre chemin relatif par rapport à BASE_DIR
        if not os.path.isabs(path):
            path = os.path.join(BASE_DIR, path)
        if os.path.exists(path):
            with open(path, 'r', encoding='utf-8') as f:
                return f.read()
    except Exception:
        pass
    return None

_simple_jwt_common = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.getenv('JWT_ACCESS_MIN', '60'))),  # 1 heure par défaut
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('JWT_REFRESH_DAYS', '30'))),  # 30 jours par défaut
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'Authorization',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}

if JWT_ALG == 'RS256':
    _priv_path = os.getenv('JWT_PRIVATE_KEY_PATH')
    _pub_path = os.getenv('JWT_PUBLIC_KEY_PATH')
    _priv_pem = _read_file_or_none(_priv_path)
    _pub_pem = _read_file_or_none(_pub_path)
    if not (_priv_pem and _pub_pem):
        raise ImproperlyConfigured('For RS256, set JWT_PRIVATE_KEY_PATH and JWT_PUBLIC_KEY_PATH to valid PEM files')
    SIMPLE_JWT = {
        **_simple_jwt_common,
        'ALGORITHM': 'RS256',
        'SIGNING_KEY': _priv_pem,
        'VERIFYING_KEY': _pub_pem,
    }
else:
    SIMPLE_JWT = {
        **_simple_jwt_common,
        'ALGORITHM': 'HS256',
        'SIGNING_KEY': os.getenv('JWT_SIGNING_KEY', SECRET_KEY),
    }

# Redis Configuration
# Note: La configuration CACHES est définie plus bas (ligne ~815)
# avec un fallback vers LocMemCache si Redis n'est pas disponible
# Railway fournit REDIS_PUBLIC_URL (accès externe) et REDIS_URL (accès interne)
# On utilise REDIS_PUBLIC_URL en priorité, puis REDIS_URL, puis REDISCLOUD_URL

# Session Cache (utilise le cache configuré plus bas)
# Si Redis n'est pas disponible, utilise LocMemCache automatiquement
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# CORS configuration (adjust origins via env)
# Configuration CORS pour la production et le développement mobile
CORS_ALLOW_ALL_ORIGINS = DEBUG  # Autoriser toutes les origines en développement

# Origines autorisées en production
CORS_ALLOWED_ORIGINS = [
    "https://comparo.up.railway.app",
    "https://comparateurdeprix.com",
    "https://www.comparateurdeprix.com",
    "https://ftp.navixtechnology.com",
    "http://ftp.navixtechnology.com",  # Si HTTP est utilisé temporairement
]

# Ajouter des origines depuis les variables d'environnement
cors_allowed_origins = os.getenv('CORS_ALLOWED_ORIGINS', '')
if cors_allowed_origins:
    CORS_ALLOWED_ORIGINS.extend([origin.strip() for origin in cors_allowed_origins.split(',') if origin.strip()])

# Autoriser les requêtes depuis les appareils mobiles en développement
if DEBUG:
    CORS_ALLOWED_ORIGINS.extend([
        'http://localhost:19006',  # Port par défaut de l'émulateur Android
        'http://localhost:19000',  # Port par défaut de l'émulateur iOS
        'http://localhost:19001',
        'http://localhost:19002',
        'http://192.168.1.65:19000',  # Votre adresse IP locale pour l'émulateur
        'http://192.168.1.65:19006',
        'http://192.168.1.65:8000',   # Votre serveur Django
    ])

# Optional: trust proxies and CSRF origins if served behind reverse proxy
# Configuration CSRF
CSRF_TRUSTED_ORIGINS = [
    'https://comparo.up.railway.app',
    'https://comparateurdeprix.com',
    'https://www.comparateurdeprix.com',
    'https://ftp.navixtechnology.com',
    'http://ftp.navixtechnology.com',  # Si HTTP est utilisé temporairement
]

# Ajouter des origines CSRF depuis les variables d'environnement
env_csrf_origins = os.getenv('CSRF_TRUSTED_ORIGINS', '')
if env_csrf_origins:
    CSRF_TRUSTED_ORIGINS.extend([o.strip() for o in env_csrf_origins.split(',') if o.strip()])

# Ajouter les origines de développement mobile en mode debug
if DEBUG:
    CSRF_TRUSTED_ORIGINS.extend([
        'http://localhost:19006',
        'http://localhost:19000',
        'http://localhost:19001',
        'http://localhost:19002',
        'http://192.168.1.65:19000',
        'http://192.168.1.65:19006',
        'http://192.168.1.65:8000',
        'http://192.168.1.65:8001',
    ])

# Google Maps API key (used for Distance Matrix / JS Maps)
GOOGLE_MAPS_API_KEY = os.getenv('GOOGLE_MAPS_API_KEY')

# Cache (Redis si disponible en prod, sinon cache local mémoire en dev)
# Vérifier si Redis est disponible avant de l'utiliser
# Priorité: REDIS_PUBLIC_URL (Railway public) > REDIS_URL (Railway internal) > REDISCLOUD_URL
# Ne JAMAIS utiliser localhost en production Railway
_railway_env_check = bool(os.getenv('RAILWAY_ENVIRONMENT') or os.getenv('RAILWAY_PROJECT_ID'))
REDIS_URL = (
    os.getenv('REDIS_PUBLIC_URL') or 
    os.getenv('REDIS_URL') or 
    os.getenv('REDISCLOUD_URL')
)
# En production Railway, ne pas utiliser de fallback localhost
if not REDIS_URL and _railway_env_check:
    import logging
    _logger = logging.getLogger(__name__)
    _logger.warning("⚠️  REDIS_URL non défini sur Railway. Le cache Redis ne sera pas disponible.")
# Permet d'utiliser une base Redis distincte pour le cache Django si souhaité
REDIS_CACHE_URL = os.getenv('REDIS_CACHE_URL') or REDIS_URL

# Tester la connexion Redis si disponible (avec timeout court pour ne pas bloquer le démarrage)
USE_REDIS_CACHE = False
import logging
logger = logging.getLogger(__name__)

# Log des variables d'environnement Redis pour le débogage (sans exposer les mots de passe)
_redis_public_url_set = bool(os.getenv('REDIS_PUBLIC_URL'))
_redis_url_set = bool(os.getenv('REDIS_URL'))
_rediscloud_url_set = bool(os.getenv('REDISCLOUD_URL'))
_redis_cache_url_set = bool(os.getenv('REDIS_CACHE_URL'))
logger.info(f"Variables Redis détectées - REDIS_PUBLIC_URL: {_redis_public_url_set}, REDIS_URL: {_redis_url_set}, REDISCLOUD_URL: {_rediscloud_url_set}, REDIS_CACHE_URL: {_redis_cache_url_set}")
if REDIS_CACHE_URL:
    # Afficher l'URL Redis masquée pour le débogage
    if '@' in REDIS_CACHE_URL:
        _debug_url = 'redis://***@' + REDIS_CACHE_URL.split('@')[-1]
    else:
        _debug_url = REDIS_CACHE_URL.replace('redis://', 'redis://***@').replace('rediss://', 'rediss://***@')
    logger.info(f"REDIS_CACHE_URL configurée: {_debug_url}")
else:
    logger.info("REDIS_CACHE_URL est None ou vide - utilisation du cache local")

if _redis_driver_available and REDIS_CACHE_URL:
    # Nettoyer l'URL Redis (supprimer les espaces, s'assurer qu'elle commence par redis://)
    REDIS_CACHE_URL = REDIS_CACHE_URL.strip()
    if not REDIS_CACHE_URL.startswith(('redis://', 'rediss://')):
        logger.warning(f"URL Redis invalide (ne commence pas par redis:// ou rediss://): {REDIS_CACHE_URL[:50]}... Utilisation du cache local.")
        USE_REDIS_CACHE = False
    else:
        try:
            # Tester la connexion Redis avec un timeout très court
            # Utiliser from_url() pour gérer automatiquement les URLs complètes avec mot de passe
            import redis as redis_client
            test_client = redis_client.from_url(
                REDIS_CACHE_URL,
                socket_connect_timeout=2,  # Timeout court pour ne pas bloquer le démarrage
                socket_timeout=2,
                decode_responses=False
            )
            test_client.ping()
            test_client.close()
            USE_REDIS_CACHE = True
            # Masquer le mot de passe dans les logs
            if '@' in REDIS_CACHE_URL:
                # Extraire la partie après @ (host:port/db)
                safe_url = REDIS_CACHE_URL.split('@')[-1]
            else:
                # Si pas de @, c'est probablement une URL sans authentification
                safe_url = REDIS_CACHE_URL.replace('redis://', '').replace('rediss://', '')
            logger.info(f"Redis disponible à redis://***@{safe_url}, utilisation du cache Redis")
        except Exception as e:
            # Redis n'est pas disponible, utiliser le cache local
            USE_REDIS_CACHE = False
            # Masquer le mot de passe dans les logs
            if '@' in REDIS_CACHE_URL:
                # Extraire la partie après @ (host:port/db)
                safe_url = REDIS_CACHE_URL.split('@')[-1]
            else:
                # Si pas de @, c'est probablement une URL sans authentification
                safe_url = REDIS_CACHE_URL.replace('redis://', '').replace('rediss://', '')
            logger.warning(f"Redis non disponible à redis://***@{safe_url}: {e}. Utilisation du cache local (LocMemCache)")
else:
    if not _redis_driver_available:
        logger.info("Driver Redis non disponible, utilisation du cache local (LocMemCache)")
    elif not REDIS_CACHE_URL:
        logger.info("Aucune URL Redis configurée, utilisation du cache local (LocMemCache)")

if USE_REDIS_CACHE:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_CACHE_URL,
            'OPTIONS': {
                'socket_connect_timeout': 5,  # Minuscules pour redis 5.x
                'socket_timeout': 5,  # Minuscules pour redis 5.x
            },
            'KEY_PREFIX': 'comparateur_prix',
            # Note: Using Django's built-in RedisCache backend. Do not pass django-redis 'client_class' here.
        }
    }
else:
    # Fallback vers cache local en mémoire si Redis n'est pas disponible
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'comparateur-prix-local-cache',
        }
    }

# DRF renderers: garder la Browsable API en dev uniquement
if not DEBUG:
    REST_FRAMEWORK['DEFAULT_RENDERER_CLASSES'] = [
        'rest_framework.renderers.JSONRenderer',
    ]

# Logging (structured logs, JSON optional via LOG_JSON=true)
from config.optimizations.logging import get_logging_config  # noqa: E402
LOGGING = get_logging_config()

# Security hardening in production
# Note: La configuration HTTPS principale est définie plus haut (lignes 59-71)
# Cette section peut être utilisée pour des configurations de sécurité additionnelles si nécessaire
if not DEBUG:
    # Les paramètres de sécurité HTTPS sont déjà configurés dans la section précédente
    # Cette section est réservée pour des configurations de sécurité additionnelles
    pass